# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.

from enum import Enum

class ResourceType(Enum):
    NONE: ResourceType
    METAL: ResourceType
    WOOD: ResourceType
    STONE: ResourceType
    GOLD: ResourceType
