# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.

from enum import Enum

class RobotType(Enum):
    NONE: RobotType
    ROBOT: RobotType
    BUILDING: RobotType
    CASTLE: RobotType
    SIEGEFOUNDRY: RobotType
    KNIGHT: RobotType
    ELITEKNIGHT: RobotType
    MASTERKNIGHT: RobotType
    ARCHER: RobotType
    ELITEARCHER: RobotType
    MASTERARCHER: RobotType
    CATAPULT: RobotType
    TREBUCHET: RobotType
    VILLAGE: RobotType
    VILLAGER: RobotType
    ARCHERYRANGE: RobotType
    WATCHTOWER: RobotType
    SPY: RobotType
