# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.

from enum import Enum

class SourceType(Enum):
    NONE: SourceType
    TINMINE: SourceType
    COPPERMINE: SourceType
    IRONMINE: SourceType
    SILVERMINE: SourceType
    GOLDMINE: SourceType
    JEWELMINE: SourceType
    DIAMONDMINE: SourceType
    FOREST: SourceType
    DEEPQUARRY: SourceType
    SHALLOWQUARRY: SourceType
